#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y nginx

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo sed -i '/location \/ {/!b;n;c \\treturn 301 \/new_page;' /etc/nginx/sites-available/default

sudo nginx -s reload
