#!/usr/bin/env bash
# Configuration of haproxy load balancer


apt-get -y update
apt-get -y install haproxy=1.6.\*

echo '
frontend tboy.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 303660-web-01 18.233.64.67
        server 303660-web-02 52.4.93.199
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
