#!/usr/bin/env bash
# A script that prints out the hours of a particular time

hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    minute=$((minute+1))
  done
  hour=$((hour+1))
done
