#!/usr/bin/env bash
# Bash script that configures the container to not login as the root user

sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
